--Criar a seguinte estrutura em Código SQL, considerando as premissas:
--1. Livre utilização dos Tipos de Dados;
--2. Respeite os tamanhos e formatos adequados para cada Campo;
--3. Os relacionamentos devem possuir mesmo Tipo de Dado;
--4. Crie as Primary e Foreign Key conforme o Modelo;
--5. Campo CODFUN da Tabela de Empregados é de Auto Numeração;
--6. Campo COD_DEPTO da Tabela de Departamentos é de Auto Numeração;
--7. Campo COD_CARGO da Tabela de Cargos é de Auto Numeração;
--8. Campos NOME (Tabelas Empregados e Dependentes), variáveis, contendo 50 bytes;
--9. Campos SALARIO, SALARIO_INIC e PREMIO_MENSAL são Monetários;
--10. Apenas os campos OBS, FOTO E COD_SUPERVISOR aceitam NULOS;


CREATE TABLE tb_DEPARTAMENTO(
COD_DEPTO		INT			IDENTITY	NOT NULL,
DEPTO			VARCHAR(20)				NOT NULL,

CONSTRAINT	PK_tb_DEPARTAMENTO_COD_DEPTO			PRIMARY KEY(COD_DEPTO)
)

INSERT INTO tb_DEPARTAMENTO
(DEPTO)
VALUES
('ADMINISTRATIVO'),
('TECNOLOGIA'),
('JURÍDICO'),
('MARKETING'),
('FINANCEIRO')


DROP TABLE tb_CARGO
CREATE TABLE tb_CARGO (
COD_CARGO		INT					IDENTITY	NOT NULL,
CARGO			VARCHAR(50)						NOT NULL,
SALARIO_INIC	MONEY							NOT NULL,

CONSTRAINT PK_tb_CARGO_COD_CARGO					PRIMARY KEY(COD_CARGO)
)


INSERT INTO tb_CARGO
(CARGO, SALARIO_INIC)
VALUES
('COORDENADOR ADMINISTRATIVO', 2000),
('ANALISTA DE DADOS',5000),
('ESTAGIARIO DE TECNOLOGIA',3450),
('ESTAGIÁRIA EM ARQUITETURA',3450),
('ADVOGADO',8000),
('ENGENHEIRO DE VENDAS',3000),
('CONTADOR',3500)

drop table tb_EMPREGADO
CREATE TABLE tb_EMPREGADO(

COD_FUN			INT			IDENTITY		NOT NULL,
NOME			VARCHAR(50)					NOT NULL,
COD_DEP			INT							NOT NULL,
DATA_NASCIMENTO DATE						NOT NULL,
COD_DEPTO		INT							NOT NULL,		
COD_CARGO		INT							NOT NULL,
DATA_ADMISSAO	DATE						NOT NULL,
SALARIO			MONEY						NOT NULL,
PREMIO_MENSAL	MONEY						NOT NULL,
SINDICALIZADO	VARCHAR(3)					NOT NULL,
OBS				VARCHAR(100)						,
FOTO			IMAGE								,
COD_SUPERVISOR	INT									,

CONSTRAINT PK_tb_EMPREGADO_COD_FUN				PRIMARY KEY(COD_FUN),
CONSTRAINT FK_tb_DEPARTAMENTO_COD_DEPTO			FOREIGN KEY(COD_DEPTO) REFERENCES tb_DEPARTAMENTO(COD_DEPTO),
CONSTRAINT FK_tb_CARGO_COD_CARGO				FOREIGN KEY(COD_CARGO) REFERENCES tb_CARGO(COD_CARGO),
CONSTRAINT FK_tb_DEPENDENTE_COD_DEP				FOREIGN KEY(COD_DEP)   REFERENCES tb_DEPENDENTE(COD_DEP)

)
INSERT INTO tb_EMPREGADO
(NOME, DATA_NASCIMENTO, DATA_ADMISSAO, SALARIO, PREMIO_MENSAL, SINDICALIZADO, OBS, FOTO, COD_SUPERVISOR)
VALUES
('MAURICIO BARBOSA MARTINS',2004-16-07,2023-02-03,3450,1500,'SIM','ESTAGIARIO COM INTERESSE EM TECNOLOGIA',NULL,NULL),
('JEAN PIERRE COUTO RAMALDES',2004-21-07,2023-02-03,3450,1500,'SIM','ESTAGIARIO COM INTERESSE EM TECNOLOGIA E SEGURANÇA',NULL,NULL),
('REBECA VIEIRA DOS SANTOS',2003-15-07,2023-08-10,3450,1500,'SIM','ESTAGIARIA EM ARQUITETURA',NULL,NULL),
('YAGO HUNKE',1998-11-05,2021-02-02,4500,2000,'SIM','CONTADOR',NULL,NULL)


CREATE TABLE tb_DEPENDENTE(

COD_FUN			INT							NOT NULL,
COD_DEP			INT			IDENTITY		NOT NULL,
NOME			VARCHAR(50)					NOT NULL,
DATA_NASCIMENTO	DATE						NOT NULL,

CONSTRAINT PK_tb_DEPENDENTE_COD_DEP			PRIMARY KEY(COD_DEP),
CONSTRAINT FK_tb_EMPREGADO_COD_FUN			FOREIGN KEY(COD_FUN)		REFERENCES tb_EMPREGADO (COD_FUN)
)



SELECT * FROM tb_CARGO
SELECT * FROM tb_DEPARTAMENTO
SELECT * FROM tb_EMPREGADO
SELECT * FROM tb_DEPENDENTE 
